apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: keyvault-example
spec:
  backendType: azureKeyVault
  keyVaultName: hello-world
  data:
    - key: hello-service/credentials
      name: password
      property: value
