apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-secret
spec:
  backendType: secretsManager
  type: kubernetes.io/dockerconfigjson
  data:
    - key: /development/dockerhub
      name: .dockerconfigjson
