apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dockerconfig-example
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: /development/dockerhub
      name: .dockerconfigjson
