apiVersion: 'kubernetes-client.io/v1'
kind: ExtrenalSecret
metadata:
  name: hello-service
secretDescriptor:
  backendType: secretManager
  properties:
    - key: hello-service/password
      name: password
