apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gcp-secrets-manager-example
spec:
  backendType: gcpSecretsManager
  gcpProjectId: hello-service-project-id
  data:
    - key: hello-service-password
      name: password
      property: value
      version: 1