apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: hello-service
spec:
  template:
    metadata:
      annotations:
        external-secret: 'Yes please!'
  backendType: secretsManager
  data:
    - key: hello-service/password
      name: password
  dataFrom:
    - hello-service/secret-envs
