apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ibmcloud-secrets-manager
spec:
  backendType: ibmcloudSecretsManager
  data:
    # The guid id of the secret
    - key: guid
      name: username_password
      secretType: username_password
