apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ibmcloud-secrets-manager
spec:
  backendType: ibmcloudSecretsManager
  # optional: true to key secrets by name instead of by ID
  keyByName: true
  data:
    - key: my-creds
      name: username_password
      # Secret Manager secret type: username_password, arbitrary, or iam_credentials
      secretType: username_password
