apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: demo-service
secretDescriptor:
  backendType: secretsManager
  # optional: specify role to assume when retrieving the data
  roleArn: arn:aws:iam::123412341234:role/let-other-account-access-secrets
  data:
    - key: demo-service/credentials
      name: password
      property: password
    - key: demo-service/credentials
      name: username
      property: username
