apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: ssm-secret-key
spec:
  backendType: systemManager
  # optional: specify role to assume when retrieving the data
  roleArn: arn:aws:iam::123456789012:role/test-role
  data:
    - key: /foo/name1
      name: variable-name
