apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: vault
spec:
  backendType: vault
  vaultMountPoint: my-kubernetes-vault-mount-point
  vaultRole: my-vault-role
  kvVersion: 2 # defaults to 2
  data:
    - name: password
      key: secret/data/hello-service/password
      property: password
    - name: cert.p12
      key: secret/data/hello-service/certificates
      property: cert.p12
      isBinary: true # defaults to false
